### ISSUE TITLE
Add glossary that defines common and potentially ambiguous terms

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1055]
With respect to choosing variable names, it's often suggested that each word or term corresponds to a single concept, and that each concept corresponds to a single word or term.  In practice, this can be difficult when science or programming terminology is used in multiple different but somewhat related ways.  I'm wondering if it would be helpful to have a glossary or set of definitions in our documentation to help reduce potential ambiguity.  A possibility would be to put this in the development guide.

_Example 1:_ "ionization state" can refer to (1) a single ionic level, (2) all ionic levels of a single element or isotope, or (3) all ionic levels of all elements or isotopes (#1053).  

_Example 2:_  Another difficulty for me has been coming up with a word or term that encompasses both "element" and "isotope", especially in the context of ions.  I'm wondering if we could use "base atom" for this.

**Comment by namurphy** [comment]
This issue has the potential for scope creep...since it has the potential to be repurposed as a glossary for plasma science as a whole.  We'd want to carefully define the scope on the page, and probably only include terms that are relevant to code development (including some commonly used programming terms like "instance" and "instantiate" that are not widely known in the plasma community).

**Comment by namurphy** [comment]
@rocco8773 brought up a point earlier that a glossary is related to the idea of having a lexicon for different variable names (i.e. making sure that `n_e` is consistently used as the argument for electron number density, `T_i` for ion temperature, etc.).  We could possibly put both together in the same part of the docs.

**Comment by rocco8773** [comment]
Yeah, I could potentially see a combined lexicon/glossary.  I still feel a lexicon would be more beneficial to package development, because it would give some guidance to developers/contributors. 

Things I could see put into a lexicon entry....

* physical/plasma parameter name (e.g. "electron temperature")
* description of physical parameter
* primary parameter name (e.g. `T_e`)
* alternative parameter names (e.g. `Te`, `Te_arr`, etc.)
    * these name could only be used when there conflicts with the  primary 
* primary unit `K`
* `validate_quantities` settings `can_be_negative=False`
* primary parameter type `Quantity`
* alternative parameter type
* primary docstring description
* alternative docstring description

As you can see, this can runaway quickly.  I don't think every entry to the lexicon needs all this information. Some may just be a physical parameter name and description.

If we could utilize `sphinx-copybotton` for the docstrings, then a contributor could directly copy-paste a docstring.  That would be  nice!

**Comment by namurphy** [comment]
Yeah, it could runaway...just like electrons!  😸  ... ... .......  Ahem.

I'd suggest keeping the information minimal.  The more information that's up there, the more information that we have to maintain.  My thinking is that this should only include stuff that's relevant to code development for us and affiliated packages for the purposes of standardization and resolving ambiguities.  

A plasma science glossary would have wonderful educational value, though that's pretty far beyond the scope of what we're trying to do (besides what's in docstrings and example notebooks).  Perhaps one activity in the hack week could be a Wikipedia edit-a-thon, since Wikipedia seems like a much better fit for that.

**Comment by namurphy** [comment]
This was pretty much closed by #1149.
