### ISSUE TITLE
Resolve documentation warning for `Exponential.FitParamTuple`

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1197]
In recent doc builds, we've been getting this warning which needs to be resolved:
```
Warning, treated as error:
/home/runner/work/PlasmaPy/PlasmaPy/docs/api/plasmapy.analysis.fit_functions.Exponential.rst.rst:18:autosummary: failed to import Exponential.FitParamTuple
ERROR: InvocationError for command /home/runner/work/PlasmaPy/PlasmaPy/.tox/build_docs/bin/sphinx-build docs docs/_build/html -W -b html (exited with code 2)
```

**Comment by rocco8773** [comment]
I am aware of this and currently looking into it.  It's a little bizarre because this import should not even be happening.  Plus I don't get the warning on my local builds.  My suspension is it's due to how the `.readthedocs.yml` is configured and our GitHub action.

**Comment by rocco8773** [comment]
So, the documentation tests started failing about 7 days ago when Sphinx release `v4.1.0`.  I confirmed this when comparing the [last passed test](https://github.com/PlasmaPy/PlasmaPy/runs/3032207723?check_suite_focus=true) to the [first failed test](https://github.com/PlasmaPy/PlasmaPy/runs/3041743126?check_suite_focus=true).  Last passed used `sphinx==4.0.3` and all the failed tests since used `sphinx>=4.1.0`.
