### ISSUE TITLE
Consolidate requirements in a single place

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1276]
Right now, when we change requirements, we need to change them in three places:

 - `setup.cfg`
 - `requirements/*.txt`
 - `requirements/environment.yml`

As I have empirically demonstrated 😬, there's a good chance that we'll end up forgetting to update them in all three places and end up with inconsistencies, even with the comments that state the other places where things need to be changed.  

We should consolidate requirements in a single place, if there is a reasonable way to go about it.  The problem is that I don't know if there currently is a reasonable way to do this.  For example, there is information in `environment.yml` that is not contained in the other two places (i.e. which channels to use and whether packages get installed via those channels or via `pip`).  

The previous major changes to the requirements in #789 were a huge and much-appreciated improvement over what was there before, and I really like the way that the requirements are split up in each of the `setup.cfg` and the `requirements/*.txt` files, so it'd be really helpful to keep a structure like if there is a way to consolidate them.

**Comment by VladimirSiv** [comment]
Hello all,

I was just looking for an open source project to contribute to, when I stumbled upon PlasmaPy.
Awesome stuff! Reminds me of my studies of theoretical physics.

Anyway, I see that you have a problem with `setup.py` and `requirements.txt`.
They serve different purposes but can be pain to manage both independently.

As far as I know there is a way to combine them as stated here: [requirements.txt vs setup.py](https://stackoverflow.com/a/49684835/10947997)

Copying here for the sake of reference:


----
> Quoting user `init_js`:

There is one trick you may consider to avoid duplicating your list of dependencies between `requirements.txt` and `setup.py`. If you have written a fully working `setup.py` for your package already, and your dependencies are mostly external, you could consider having a simple `requirements.txt` with only the following:

```
 # requirements.txt
 #
 # installs dependencies from ./setup.py, and the package itself,
 # in editable mode
 -e .

 # (the -e above is optional). you could also just install the package
 # normally with just the line below (after uncommenting)
 # .
```

The -e is a special pip install option which installs the given package in editable mode. When pip -r requirements.txt is run on this file, pip will install your dependencies via the list in ./setup.py. The editable option will place a symlink in your install directory (instead of an egg or archived copy). It allows developers to edit code in place from the repository without reinstalling.

You can also take advantage of what's called "setuptools extras" when you have both files in your package repository. You can define optional packages in setup.py under a custom category, and install those packages from just that category with pip:

```python
# setup.py
from setuptools import setup
setup(
   name="FOO"
   ...
   extras_require = {
       'dev': ['pylint'],
       'build': ['requests']
   }
   ...
)
```

and then, in the requirements file:

```
# install packages in the [build] category, from setup.py
# (path/to/mypkg is the directory where setup.py is)
-e path/to/mypkg[build]
```

This would keep all your dependency lists inside setup.py. 

---

I hope this helps.
If I get the time I'll see if I can do something about it.

Cheers!

**Comment by rocco8773** [comment]
I agree with @VladimirSiv on the first part.  The `setup.cfg`, `requirements/*.txt`, and `environemnt.yml` all serve independent purposes, so I don't know of a good method to consolidate.  What we have now is the best "consolidated" option I could come up with at the time #789 was done.  I know there is a push to move away from the `setup.cfg` in favor of `pyproject.toml` for packaging, so maybe there's something better with that setup.

As for the `-e` suggestion by @VladimirSiv , I see this as a NO GO.  This would force `plasmapy` to be installed when a user (such as I) is just trying to install requirements.  In that case I'd just do `pip install .[docs] -e`, or the like.

**Comment by namurphy** [comment]
Thank you, @VladimirSiv!  I hadn't known about the possibility of having `requirements.txt` be a `.`.  

Have you heard anything about [poetry](https://python-poetry.org/)?  I just learned about it in the last few days and it seems like it might be able to resolve this problem by allowing us to declare dependencies in `pyproject.toml`.  I still need to find some time to read up on it to understand what it's doing.

**Comment by VladimirSiv** [comment]
@namurphy 
> Have you heard anything about poetry?

Actually a lot. I use it every day at work.
Some of the good things about poetry:
- Creates a virtualenv (uses `venv` as backend) where you can install your packages and keep everything clean. 
- It has a support for development packages through `--dev` option when adding a new package through `poetry add <package> --dev` which gives you control over your `dev` and `prod` packages
- `poetry update` updates packages and resolves dependency tree
- Has a way to script things (ref: [poetry scripts](https://python-poetry.org/docs/pyproject/#scripts)). This is useful for CI/CD pipelines and you can set githooks to run linters/tests on commit/push. Script are defined in `pyproject.toml` and can be very useful with `pytest`
- Keeps all information about packages in `poetry.lock` which you commit to your repo and that gives you control and oversight of every package version so you can always rollback if something breaks with new versions.
- You can set different package repositories (ref: [poetry repositories](https://python-poetry.org/docs/repositories/)). For example if you keep certain packages in-house or in private repos. This is useful for example for CodeArtifact in AWS where you store your packages but still want to pull open source packages from pypi.
- etc.

There is also [pipenv](https://pipenv.pypa.io/en/latest/). Basically the same thing as poetry but I think that poetry is considered better.

**Comment by namurphy** [comment]
Wow, thank you!  That's really helpful.  It sounds like I should set aside some time to learn about `poetry`.  It sounds like it could be helpful to us in a couple of different ways.
