### ISSUE TITLE
Automate testing of example code with doctest

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#128]
Python's built-in [doctest](https://docs.python.org/3.6/library/doctest.html) module includes capabilities to search through docstrings for examples that look like interactive Python sessions, and then make sure that the actual output of the examples matches what is shown in the docstring example.  This capability should be included in our continuous integration testing so that we can ensure that our example code is accurate.  This testing is especially important prior to version 0.1 since our application program interface (API) within different subpackages is evolving from month to month.  We will probably need to implement this for docstrings as well as the documentation in our `docs` directory.  The`atomic` subpackage may be a good first place to test, since there were a few recent API changes and I might have missed updating some of the examples.

Thank you!
-Nick

**Comment by StanczakDominik** [comment]
Isn't this on by default? I thought it was. I'll check for it anyway and
make sure.

On Sep 30, 2017 20:28, "Nick Murphy" <notifications@github.com> wrote:

Python's built-in doctest <https://docs.python.org/3.6/library/doctest.html>
module includes capabilities to search through docstrings for examples that
look like interactive Python sessions, and then make sure that the actual
output of the examples matches what is shown in the docstring example. This
capability should be included in our continuous integration testing so that
we can ensure that our example code is accurate. This testing is especially
important prior to version 0.1 since our application program interface
(API) within different subpackages is evolving from month to month. We will
probably need to implement this for docstrings as well as the documentation
in our docs directory. Theatomic subpackage may be a good first place to
test, since there were a few recent API changes and I might have missed
updating some of the examples.

Thank you!
-Nick

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PlasmaPy/PlasmaPy/issues/128>, or mute the thread

**Comment by pohzipohzi** [comment]
Hi if im getting you correctly, we can add a `pytest.ini` file with the lines:

`[pytest]
 addopts = --doctest-modules`

to automatically add doctest integration for pytest (see [this](https://docs.pytest.org/en/latest/doctest.html))

I made a PR with the relevant changes for the atomic package, hopefully that's what you were looking for :)
