### ISSUE TITLE
Discuss how to modify CSS file in documentation guide

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1318]
At present we use one CSS file to define custom styles for our documentation: `docs/_static/sphinx_rtd_overrides.css`.  In #1287 I'm attempting to change this file to improve contrast, but it took me ≳1.5 hours to add ∼8 lines in the file since I had never used CSS before, and I still haven't finished 😕.  This was partially because our docs take a while to build, and also because I didn't know enough to know what I didn't know 😐.  

It'd be helpful to discuss how to modify our CSS file in our documentation guide.  When possible, we should link to pre-existing resources like this [CSS tutorial](https://www.youtube.com/watch?v=1PnVor36_40) so that we don't need to write or maintain it.  At the very least, we should add (or link to) information on how to include a style element by inspecting the page source, and how to define a new style override in a way which assumes no prior knowledge of CSS.  

I don't expect this to be used often so it shouldn't be in a prominent position, and we could possibly add an admonition/note saying that this section could be skipped by most readers of the doc guide.

**Comment by StanczakDominik** [comment]
> we could possibly add an admonition/note saying that this section could be skipped by most readers of the doc guide.

At this rate we'll have a whole bunch of these, and I really don't want the dev docs to outgrow PlasmaPy itself! With all development, there's usually a fair amount of websearching involved - can we really aim to provide the answers to all possible relevant web searches?

Besides, for this kind of issue, I'd be searching for "sphinx quick test css adjustment" rather than "sphinx quick test css adjustment **plasmapy**". In other words, I suspect putting this kind of thing in the documentation, where it's probably not a priori expected to be found, is not really useful.

Github issues are searchable though, so I think it's perfectly fine to just document this kind of problem as a quick github issue, though!

---

I think this problem can be solved in an easier way. AFAIK CSS is not modified during the Sphinx build, just statically attached to the built docs (as suggested by the location in `docs/_static`) and then looked up at browser runtime. Having built the docs via `make html`, we can go to `_build/html/_static/rtd_theme_overrides.css`, open that up in ~~vim~~ your editor of choice, modify (say, increase `font-size` of `div.pkgnav` from `1em` to `4em` for visibility), save and refresh the page in your browser. And that does it! No rebuild needed.

So I'll close this one for now, unless you disagree, in which case feel free to reopen!
