### ISSUE TITLE
Do we need a `import plasmapy` GitHub Action check?

### ISSUE THREAD

**Issue by rocco8773** [PlasmaPy/PlasmaPy#1447]
I'm a little puzzled how all the checks for PR #1444 passed when an `ImportError` was raised when importing `plasmapy.formulary.parameters` (see PR #1446).  I'm thinking we should add to our CI checks a check on importing `plasmapy` to ensure it imports without error.

@namurphy @StanczakDominik Thoughts?

**Comment by namurphy** [comment]
I like it.  Given my history of directly inspiring the Astropy 4.3.1 bugfix release due to accidentally deleting the `astropy.units.imperial` import in `__init__.py`, I'd say this check (and perhaps even checks that our subpackages are in the top-level namespace) would be worth having.  With that said, I've *probably* learned my lesson.  Probably.

**Comment by namurphy** [comment]
I'm wondering if there's a pytest extension for this...

**Comment by namurphy** [comment]
Closed by #1501.
