### ISSUE TITLE
Migrate tests to using unittest module?

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#150]
I think it'd be better to use a proper unit testing module like the built-in unittest, rather than using asserts with no feedback on tests passed. I have some familiarity with this module and could readily write some example tests that you can then build off of.

Thoughts?

**Comment by StanczakDominik** [comment]
I don't think that's a flaw in pytest - astropy and matplotlib both use it, so I don't think it's necessary to switch to unittest (I'd be happy to be convinced otherwise, though!) I do think it's likely that our tests can be badly written! Can you point out some of the worse ones?

Perhaps instead of doing tests like this:

    assert result == 42

it would be enough to pay attention to write them in this way everywhere:

    assert result == 42, "result is not the answer to everything"

That way the string message is printed out whenever this test fails. Would that be okay?

**Comment by lemmatum** [comment]
There are a few issues with assert. One big one is not being able to continue the testing after failure of an assert statement. Modules like pyTest and unittest will crank through all the tests and tell you how many successes, how many failures and where.
There are other advantages to modules like pyTest and unittest, such as being able to setup and teardown tests (very useful for testing classes/objects), and integrate tests for a package under a single script without having to explicitly call each function in every module in every subdirectory.

I agree that adding comments for test failure is a must, but I don't see a way to resolve the above issues (especially inability to elegantly fail a test) with assert statements. I'm not sure what the people at astropy and matplotlib are doing, but a quick search brings up modules that use [pyTest](https://github.com/matplotlib/matplotlib/blob/e69ea36995a76c37b928f9cab9af1161f8d36e05/lib/matplotlib/tests/test_marker.py) in matplotlib.

**Comment by lemmatum** [comment]
btw, this ties into the whole `if __name__ == "__main__":` issue, which is that using these modules (e.g. pyTest), when you run a test script directly they'll tell you the successes and failures within that test script. At the moment the test scripts are just a bunch of functions that don't get run (at least in test_quantum.py).

**Comment by lemmatum** [comment]
I think this and the `if __name__ == "__main__":` issues are mainly my ignorance of how pyTest works. With unittest you run the module directly using `python test_quantum.py`, whereas with pyTest you call `pyTest` instead. So yea, I agree pyTest is good, just need to cleanup and add more informative messages when tests fail.

**Comment by StanczakDominik** [comment]
Did you remove a bunch of your posts in this discussion? I had email notifications for them and can't find them here right now :smile:

I do think we need to clean up our testing process and documentation, it's pretty darn opaque at the moment. I'll try to get on that ASAP.

There was also, I believe, a good point you raised about tests within a function  stopping at an assertion and not running the latter ones. That's because our tests can be improved!

Here's a made up example for a cool math conjecture I heard of a while ago, that was basically proven by proving it's true if the Riemann hypothesis it's true, and then proving it's true also if the Riemann hypothesis is false, so the conjecture is true anyway regardless of the Riemann hypothesis.

As we often do it right now:

    def test_proof_by_riemann_hypothesis():
         assert proof_by_riemann(False) # if this step fails, the test stops
         assert proof_by_riemann(True) # and you have to run this again

Whereas in pytest what you technically should do to make the tests independent:

    def test_proof_if_riemann_false():
         assert proof_by_riemann(False)
    def test_proof_if_riemann_true():
         assert proof_by_riemann(True)

but that's a lot of typing so what you actually do is use pytest parametrization, which (along with pytest fixtures, for more reusability) are the best thing since sliced bread:

    @pytest.mark.parametrize("truth", [True, False])
    def test_proof_if_riemann(truth):
         assert proof_by_riemann(truth)

And both of these are going to run regardless of failures, which is awesome!

Of course, with qualitatively different tests you would use either separate functions or you'd pass in pairs of inputs and expected values:


    @pytest.mark.parametrize("truth,expected", [(True, True),
                                                                            (False, True)])
    def test_proof_if_riemann(truth, expected):
         assert proof_by_riemann(truth) == expected


I'm going to have to adapt this into our docs somewhere.

**Comment by lemmatum** [comment]
>  you remove a bunch of your posts in this discussion? I had email notifications for them and can't find them here right now 😄

Mistakes were made! I didn't fully appreciate the power of pyTest 😄 

Might be valuable to add how to setup and run tests via pyTest under the contributing doc #151 

> There was also, I believe, a good point you raised about tests within a function stopping at an assertion and not running the latter ones. That's because our tests can be improved!

Looks like I can stumble upon good points sometimes, even when confused!
I quite like the Riemann example you gave. So for the tests we currently have written, do you think the solution is to split them up into a bunch of tiny functions? I think there might be a better way to do this. In unittest you write a bunch of tiny methods to test different aspects of a single function/class, but this is all written under a larger function (or class, I don't remember). Then unittest just runs the larger function and you can name the tiny methods something simple without having to explain that they are testing function X. There's probably a way to do something similar in pyTest.

**Comment by StanczakDominik** [comment]
Sure, there probably is. I'll have to dig deeper into them pytest docs and look into that!

**Comment by Cadair** [comment]
You can have tests in classes with pytest, but personally I do not like that, using pytest fixtures and a bunch of functions is generally enough. Too much setup and tear-down code can lead to trouble.

In general (having just had a *quick* scroll through) you do need to split up the tests in to lots of little ones. Also worth knowing how to use is [pytest parametrize](https://docs.pytest.org/en/latest/parametrize.html) and also [hypothesis](http://hypothesis.readthedocs.io/).

**Comment by StanczakDominik** [comment]
I'm going to close this for now, but if there's anything more to discuss here I'll gladly reopen it!
