### ISSUE TITLE
Extend `gyroradius` to the relativistic limit

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1537]
I just noticed that [`gyroradius`](https://docs.plasmapy.org/en/latest/api/plasmapy.formulary.lengths.gyroradius.html?highlight=gyroradius#plasmapy.formulary.lengths.gyroradius) is presently only applicable in non-relativistic cases, but there are a lot of applications in astrophysics that involve relativistic particles in magnetic fields, and it would be helpful to be able to calculate the [gyroradius in the relativistic limit](https://en.wikipedia.org/wiki/Gyroradius#Relativistic_case) as well: 

<img src="https://render.githubusercontent.com/render/math?math=r_g = \frac{p_\perp}{|q|B} = \frac{\gamma m v_\perp}{|q|B}">

I'm also wondering if we could have the Lorentz factor γ be a keyword-only argument that could be used instead of the velocity.

**Comment by chrisarridge** [comment]
I can do this as a first contribution to PlasmaPy :)

**Comment by rocco8773** [comment]
Why not just have the functionality check the speed and switch over to a relativistic form when `v/c > 0.1`? ... You might still want a `use_relativistic` boolean keyword to manually force the situation.  Of course, you'd then need to use a `PhysicsWarning` or `RelativisticWarning` when trying to force the incorrect regime.

I think that would be less error prone and more explicit than a Lorentz keyword.

**Comment by namurphy** [comment]
My motivation for having an optional Lorentz factor keyword is that when the velocity gets really close to c, we could end up with roundoff error in the calculation of the Lorentz number, and thus the gyroradius too.  One of the use cases I'm thinking of is for ultra-high energy cosmic rays which have E ≲ 10<sup>21</sup> eV so that the velocity is ridiculously close to c.  ⚡  For a case like that, the Lorentz number (or perhaps the momentum?) would be a more natural input with a much lower chance of roundoff error.

I like the idea of having a `use_relativistic` keyword or perhaps just `relativistic`.

**Comment by StanczakDominik** [comment]
My problem with having this work as `relativistic_gyroradius if v/c > 0.1 else slow_gyroradius` is that it'd introduce an artificial discontinuity at `v/c = 0.1`, which is arbitrary and nonphysical...

Perhaps we should do it the other way around? Since for small velocities the relativistic gyroradius converges to the nonrelativistic one, we could have the relativistic one be the default and have a flag saying `no_really_ignore_Einstein_I_actually_want_the_nonrelativistic_one_for_comparison_purposes`. The naming's negotiable.

**Comment by chrisarridge** [comment]
I have the same feeling about an artificial step at ``v/c=0.1``, especially if arrays of ``v`` were passed in, and I like the option of defaulting to the relativistic calculation but having the facility to set a ``nonrelativistic`` boolean.

If we set by the Lorentz factor then we would still need to calculate ``v`` from that for the calculation and could give us ``v>c`` with roundoff, albeit less of an issue that ``v>c`` if we directly computed the Lorentz factor from a given ``v`` as would could end up with a complex factor.  I wonder about providing ``beta=v/c`` as the independent variable, rather than the Lorentz factor.  It avoids roundoff if ``v~c`` but also allows us to trivially set ``v`` in the calculation?  I might run some tests against high precision mathematics to see how close we have to get in different scenarios before we hit such issues.

**Comment by rocco8773** [comment]
`v/c<0.1` is not an artificial step.  If you expand the Lorentz factor and take the common approximation `v/c<<1` (aka by common practice `v/c<0.1`), then you get back `1` (or the classical limit).

My "issue" with applying the Lorentz factor all the time, is that user will be expecting the classical version, and might unexpectedly get the relativistic version.  There will also need to be some kind of reconciliation with the documentation that includes notes about both versions.

I'm not keen on the idea of adding a `beta` or `Lorentz` keyword, since we're just asking for information that may conflict with the other input arguments.  I think a more appropriate step is to calculate `v` based on input arguments and throw errors and/warnings depending on what is calculated.

My idea with `use_relativistic` is that it's three valued: (1) default to `None` which does the automatic switching; (2) `False` which always gives non-classical; and (3) `True` which always gives relativistic.  Of course all these scenarios would need to pair with appropriate exceptions and warnings to make the functionality work logically.  To me this seems like a have your cake and eat it too solution.

By no means do I think my idea is the only way forward, it's just the one that makes most sense to me on face value.  @chrisarridge I think you should just proceed with what makes the most logical sense to you, and then, as always, we'll refine in the PR review.

**Comment by StanczakDominik** [comment]
> `v/c<0.1` is not an artificial step. If you expand the Lorentz factor and take the common approximation `v/c<<1` (aka by common practice `v/c<0.1`), then you get back `1` (or the classical limit).

While this is true in a "common practice, conventional physics wisdom, generally unquestioned assumption" sense, it's still an approximation and not "true" in a strict, numerical sense. Here's an overview of the difference (for a proton at B = 1 T):

![gyroradius](https://user-images.githubusercontent.com/11289391/167799830-fc9060a7-b5c9-42fa-831a-7b27c72bd9e1.png)

An error of 0.5% (that's the Lorentz factor at v/c = 0.1) just below the cutoff is, of course, not "large", but I can promise you, as an inattentive and documentation-averse computationalist implementing code down the line I'd be concerned over where that's coming from! But we can get rid of it pretty easily, so why not? Of course, whether you'd treat is as an error comes down to your other point:

> My "issue" with applying the Lorentz factor all the time, is that **user will be expecting the classical version**, and might unexpectedly get the relativistic version.

When I imagine myself trying to analyse something and needing to calculate the gyroradius, I think I'd want the "closest value to the actual true gyroradius" first and any particular assumptions second. If my final output can be 1% more accurate for the low price (in developer-attention units) of using `gyroradius` rather than just `m * v / q / B`, I'd be sure to take it.

To put it another way, since the nonrelativistic worldview is a strict subset of the relativistic one, I can't imagine a situation where taking the relativistic assumption would harm you if what you're concerned is representing a physical system as close to the truth as possible.

Either your parameters are in the relativistic regime, in which case you'd need to pay attention that you're using the relativistic calculation anyway, or they aren't, in which case you lose nothing, except for a couple CPU cycles spent mostly on a square root (a 33% relative increase of 0.66 ms in my quick hackish implementation).

The relativistic correction is a great example of complexity that doesn't need to be exposed to the user, and thinking about it now I'd advocate for applying those assumptions everywhere, if they come essentially for free.

One caveat: if you have a bunch of parameters to calculate and some of them use relativistic assumptions and some of them don't, I could imagine possible worrisome issues, cancellations etc.

**Comment by MuhammadHMasood** [comment]
Hi, I've noticed that no-one has worked on this for a while, would it be ok if I tried doing this as my first commit?

**Comment by namurphy** [comment]
> Hi, I've noticed that no-one has worked on this for a while, would it be ok if I tried doing this as my first commit?

Yes, that would be great!  Thank you!

**Comment by MuhammadHMasood** [comment]
Given that relativisticbody is now a thing, would it be a good idea make the updated gyroradius function work by accepting both particles and relativistic bodies and if not a relativistic body then converting the particle to a relativistic body to get the lorentz factor unless they specifically make it nonrelativistic?

**Comment by MuhammadHMasood** [comment]
actually i think ill just provide an optional lorentz factor keyword

**Comment by namurphy** [comment]
> actually i think ill just provide an optional lorentz factor keyword

That seems like a good approach.  We do want to have interoperability with `RelativisticBody`, but I'm not sure if it would be better for `gyroradius` to accept a `RelativisticBody`, or to have a `RelativisticBody.gyroradius(Vperp=...)` method.

**Comment by MuhammadHMasood** [comment]
> I'm also wondering if we could have the Lorentz factor γ be a keyword-only argument that could be used instead of the velocity.
Wouldn't calculating velocity from lorentz factor result in some error or does it work out?

**Comment by namurphy** [comment]
> Wouldn't calculating velocity from lorentz factor result in some error or does it work out?

`RelativisticBody` is able to get the Lorentz factor from the velocity, if I'm remembering right.  The main issue is that if $γ$ is really large, then the velocity you'd get would be within rounding error of $c$, which might lead to a floating point math warning.

**Comment by MuhammadHMasood** [comment]
I am also gonna edit part of the logic because right now it doesn't raise an error if both vperp or temperature are not passed and im pretty sure it should raise an error instead of just returning a nan radius

**Comment by MuhammadHMasood** [comment]
although i guess since none of them are passed its actually the logic i want
since i want to get it from lorentz force if neither are provided

**Comment by namurphy** [comment]
> I am also gonna edit part of the logic because right now it doesn't raise an error if both vperp or temperature are not passed and im pretty sure it should raise an error instead of just returning nan gyroradius

Agreed!  That seems like a good situation for an exception with a descriptive error message.
