### ISSUE TITLE
Journal publications on plasmaPy

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#159]
This project is quite wide in scope with many modules that have and will involve a lot of work. Are there any plans for publishing this stuff? To me, it would be cool if there was an over-arching plasmapy article and then separate articles describing the functionality of some of the more complex modules.
One place to consider publishing is the [Journal of Open Research Software](https://openresearchsoftware.metajnl.com/) which takes metapapers on reusable codes used in research with the expectation that they are documented, archived, and open source.

Has this question been addressed elsewhere? This might be a good way to attract attention to plasmapy in the future and to reward significant contributions with highly citable papers.

**Comment by namurphy** [comment]
I completely agree!  I have personally been wondering if version 0.2 would be a good time to publish an article that describes the overall project.  I heard a lot about the [Journal of Open Source Software](http://joss.theoj.org/) at SciPy 2017, which is another possibility.  Physics of Plasmas also allows open access publications for a higher publication fee, which might be worth it since it would reach many more plasma physicists.  We can also look for inspiration from [Astropy's v0.2 paper](https://doi.org/10.1051/0004-6361/201322068) and [SunPy's v0.5 paper](https://doi.org/10.1088/1749-4699/8/1/014009) too.  Thank you for bringing this up!

**Comment by lemmatum** [comment]
Are there any particular physics milestones for v0.2 which you would want to include in a plasmapy paper? (both milestones which currently exist and ones you can think of which would look good in a publication)
Those are all great links! I shall look to them for inspiration for my own projects as well! 😃

**Comment by lemmatum** [comment]
[Zenodo](https://zenodo.org/) may be another platform for publishing code/article.

**Comment by lemmatum** [comment]
If we get financial assistance from GSOC, they should be mentioned in the acknowledgements.

**Comment by lemmatum** [comment]
As per our video conference on 2018-05-08, we want to publish in Physics of Plasmas for v0.2. The paper will be in LaTeX/REVTex.

We should start planning PlasmaPy features which can be translated into figures for the paper which convey a "wow factor".
