### ISSUE TITLE
Add useful spectroscopic functions

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#162]
- [ ] Planckian function
- [ ] Bremsstrahlung estimator
- [ ] Saha-Boltzmann function
- [ ] Bragg diffraction function
- [ ] Grating diffraction function
- [ ] Spectral line LTE test functions
- [ ] profiles (e.g. Voigt, Lorentzian, Gaussian)

**Comment by namurphy** [comment]
Yes, we definitely need spectroscopic analysis capabilities!    All of the functions you are suggesting would be very helpful.

In the long run, I'm wondering how much we could partner with Astropy and SunPy since spectroscopy is important for these fields as well as laboratory plasma physics.  It would be great if all three of our packages could have a shared spectroscopy framework.

Cross-references: https://github.com/PlasmaPy/PlasmaPy/issues/18, https://github.com/PlasmaPy/PlasmaPy/issues/52

**Comment by lemmatum** [comment]
Yea, I was thinking about that as well, since spectroscopy is so rich with content. So far I haven't seen a broad spectroscopy package that integrates multiple databases, queries NIST, has functions useful for experimentalists, etc.

What do you think makes most sense?
* Start an independent spectroscopy package
* Start by writing spectroscopy functions in plasmapy and then split it off into its own entity

The former has some initial overhead, but the latter may create more work in the long run with re-arranging and re-writing modules. I'd be willing to try my hand at setting up and managing the project.

**Comment by StanczakDominik** [comment]
I'm just going to say that the name SpectroscoPy pretty much writes itself.

**Comment by lemmatum** [comment]
@StanczakDominik perfect name! I will have to setup this project in the near future!

**Comment by namurphy** [comment]
There are a couple of existing packages/subpackages that are worth looking into as well:
 - https://github.com/astropy/specutils
 - http://docs.sunpy.org/en/stable/code_ref/spectra.html

@StanczakDominik - Great name!  At one point I had hoped that Astropy could be renamed as "Py in the Sky".

**Comment by namurphy** [comment]
@wtbarnes has started working on [fiasco](https://github.com/wtbarnes/fiasco) which would be a Python interface for the CHIANTI atomic database in the Astropy/SunPy ecosystem.  [ChiantiPy](https://github.com/chianti-atomic/ChiantiPy) also acts as an interface.  There's also [pyatomdb](http://atomdb.readthedocs.io/en/master/) which is an interface with AtomDB.  These databases are used pretty widely in solar physics and astrophysics.

**Comment by lemmatum** [comment]
I saw you mention those in another issue. Unfortunately I don't think they support optically thick plasmas. :stuck_out_tongue:
It'd be cool to have some opacity codes.

**Comment by namurphy** [comment]
Agreed.  Codes that deal with opacities and radiative transfer would be phenomenal, and even radiation hydrodynamics which comes up all the time in plasma astrophysics.  We still have to figure out how to deal with all of the ridiculous amounts of atomic data that we need for all of this though...  😿

**Comment by wtbarnes** [comment]
While most of the common *calculations* done in CHIANTI would not be valid in the optically thick regime, It is possible that some of the *data* in CHIANTI (and AtomDB?) could still be used to do radiative transfer calculations. One would need to be careful about making sure there are no optically-thin assumptions leaking in.

**Comment by lemmatum** [comment]
Probably just need to bite the bullet an and make an opacity table generator. It would have be tested against other tables, like SESAME, PROPACEOS, etc. All the ones I've seen are proprietary in one way or another.

I think most other atomic data can be obtained from NIST and any holes in NIST can be filled in with other tables or approximations (like with H-like atomic data). There is probably some sensible way of making term symbols a unique identifier for atomic energy levels and then just dumping all the data into an HDF5 file (faster for computation) or relational database (faster for filtering by different columns).

**Comment by lemmatum** [comment]
BTW the matter in extreme conditions community has similar issues with equation of state tables being opaque. Last conference I was at, they mentioned how people cite tables but there is no unique identifier and therefore no way to know which version or subcomponent of a table people used. So we should take these issues into consideration if we use or generate these databases.

**Comment by wtbarnes** [comment]
Is the NIST data easily accessible? I know they have a web portal, but from what I can tell there's no way to just download the whole database (or hit an API endpoint or whatever).

Because CHIANTI is distributed as a bunch of ASCII files, my approach has been to rebuild the entire database as an HDF5 file and then provide an API to this file. So far this has worked quite well. 

I worry about having a separate package for each set of atomic data, whether for optically thin or optically thick plasmas. Taken too far, I'm worried that this would just recreate the problem we already have where every dataset has to be accessed and parsed a slightly different way. It would be great if there was a single package, or at the very least an agreed upon API format, for accessing and parsing this data. This would make comparisons across databases and interoperability between datasets massively more convenient. (I've created a [related issue on the fiasco page](https://github.com/wtbarnes/fiasco/issues/11))

**Comment by wtbarnes** [comment]
Yes this whole business of databases just being updated and old versions not being accessible or maintained is a big problem. The current state of CHIANTI is that no old versions of the database are supported by the current software and the old software is not really made available... From what @lemmatum has said, sounds like this problem is quite pervasive throughout the plasma community as well.

**Comment by lemmatum** [comment]
Yea, there isn't an efficient interface to the NIST data like an API. But I do have some scripts for querying the data and then parsing it via HTTP. Astroquery has some functions for that as well. Also, I could just contact the guys over at NIST and ask them for a dump of the database files. They seemed willing to send me some smaller chunks in the past, like ionization data.

I agree! The important thing is to figure out some common denominator between all these atomic databases and then store/query the data through that system. Could it be as easy as looking at what data columns these databases have?

**Comment by lemmatum** [comment]
@StanczakDominik [spectroscopy](https://pypi.python.org/pypi/spectroscopy) is currently occupied on PyPI and unfortunately pip is case insensitive 😭 . What do you figure our odds are of getting the developer to rename their package? 😀

**Comment by wtbarnes** [comment]
@lemmatum Re: interfacing with multiple databases, the calculations/derived quantities that people end up actually using from all of these databases are largely the same, e.g. ionization and recombination rates, level populations, etc. 

I think a sensible approach would be to have a common high-level abstraction that the user interfaces with, e.g. `Ion` and `Element` classes, and then having database specific backends. 

In this way, you force all of the different sources to "speak the same language" and the package does the translation to a common language behind the scenes.

**Comment by lemmatum** [comment]
@wtbarnes , yup! And then also need a way to identify particular energy levels... probably electron configuration + [term symbol](https://en.wikipedia.org/wiki/Term_symbol). It would also be useful to have aliases for common nomenclature like Ly-alpha, Li-gamma, etc.

**Comment by wtbarnes** [comment]
@lemmatum That's a great idea as well. In fiasco, I've implemented the ion and element abstractions that I mentioned (see [this notebook for a brief demo](https://gist.github.com/wtbarnes/1a9acc43381a33d016843c666150e8e9)) and I think it is a really nice way of interfacing with the data and is very intuitive. I hadn't thought too much about applying this same logic to the energy levels of an ion, but it is a very natural extension.

The more I think about this, the less a database-specific atomic data package makes sense. Of course imposing another degree of abstraction makes this problem even harder and it wasn't simple to begin with!

A relevant question though: would PlasmaPy want to support such functionality? This seems more well-suited for an external package.

**Comment by lemmatum** [comment]
@wtbarnes No I don't think PlasmaPy should support this functionality. I am planning on starting a separate spectroscopy project which people from various projects who might find this useful(e.g. PlasmaPy, AstroPy, SunPy) could contribute to.
In that project I would like to have this abstraction layer describing electron configurations and then transitions which emit/absorb photons could be described by feeding two such configurations as initial and final states. This abstraction could then be applied over various spectral/atomic databases. I would also like to include line shape and opacity databases with similar abstractions.

**Comment by wtbarnes** [comment]
@lemmatum It seems well-suited for its own package.

What you're describing sounds a lot like what I am aiming to do with fiasco though of course my use case is currently limited to (optically thin) CHIANTI data. However, I think the approach I've taken could be easily generalized to other databases and to more involved calculations needed for radiative transfer.

**Comment by lemmatum** [comment]
Thoughts on how to coordinate to minimize reproduced effort?

**Comment by namurphy** [comment]
@wtbarnes, @lemmatum - This is a fantastic conversation!  My suggestion would be to create an affiliated package within one of the Astropy, SunPy, or PlasmaPy frameworks.  That way you wouldn't have to completely build new organizational infrastructure (which is a huge amount of work, we're discovering).  I personally would be happy for us to create an atomic data/spectroscopy package within the [PlasmaPy project](https://github.com/PlasmaPy).  It would be good to check what already exists in Astropy and SunPy since it might be possible to build upon existing tools.

I've mentioned to @wtbarnes that a friend and I are interested in developing a Python tool for time-dependent non-equilibrium ionization modeling, especially of astrophysical plasmas.  If the small grant proposal we submitted this year is accepted, it is very likely that we would develop these capabilities within a community atomic data/spectroscopy package rather than developing a standalone package as we had proposed.

**Comment by antoinelpp** [comment]
Hi everyone !
I'm not so into spectroscopy, but I ask my colegues, and they told me about another package of spectroscopy functions : https://bitbucket.org/OES_muni/massiveoes

I hope it can help you.

**Comment by lemmatum** [comment]
@namurphy , I've created the new project under the PlasmaPy organization as per your suggestion https://github.com/PlasmaPy/SpectroscoPy

I've got a decent idea of how I want to begin structuring the project so I'll initiate some pulls to give it a directory structure. Otherwise feel free to make edits, open issues, etc.

**Comment by namurphy** [comment]
Cool!  One possibility would be to use or look into [Astropy's package template](https://github.com/astropy/package-template) as a place to get started.

**Comment by lemmatum** [comment]
@namurphy I've initialized the project using a combination of astropy template package and PlasmaPy's files. It seems to run setup.py without issues. Take a look!

**Comment by lemmatum** [comment]
I'm closing this issue as it should now be handled by [SpectroscoPy](https://github.com/PlasmaPy/SpectroscoPy). If you guys want to discuss further I recommend adding to one of the already created issues or generating a new one.

**Comment by Cadair** [comment]
Just to quickly chime in here, there is a lot of work going on in representing spectroscopic data in python within the astropy community. As much as it's always a lot of work, I recommend dropping an email to the astropy list to work out where your plans fit in with other efforts in the community. :)

**Comment by wtbarnes** [comment]
@Cadair do you know of any other affiliated packages besides specutils that are doing this?

**Comment by lemmatum** [comment]
Just sent a message to the astropy mailing list. Let's see what we get!

**Comment by Cadair** [comment]
@wtbarnes no code yet but there is this APE: https://github.com/astropy/astropy-APEs/pull/28 and a lot of discussion in various places that has led to it.
