### ISSUE TITLE
Exotic particles

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/PlasmaPy#174]
It might be worthwhile to add some exotic particles to the particle library, such as muons, tauons, and neutrinos.

Opinions?

**Comment by namurphy** [comment]
I suspect that cosmic ray scientists (including many plasma astrophysicists) would use this functionality.  This sounds like a good idea to me, especially since the implementation should be rather light.

**Comment by namurphy** [comment]
To implement this, I think we could create a file called `particles.py` which would have electrons, neutrinos, muons, tau particles and their anti-particles.  This would also be really helpful to account for all of the irksome special cases that keep showing up.  I've also been wondering how to cleanly account for all of the different aliases that are out there, some of which are cases sensitive and others of which are case-insensitive.  I tentatively assigned this to myself since there's more work that I want to do to clean up and refactor the atomic subpackage.

**Comment by StanczakDominik** [comment]
Does #221 solve this, or is there more to be done here?

**Comment by namurphy** [comment]
#221 partially addressed this issue by adding in dictionaries for the different particles, but there is still work to do to make sure the methods in the atomic subpackage accesses the data in these dictionaries.  Right now none of the existing public methods can get the mass of a muon, for example.  I was planning on adding `particle_symbol` and `particle_mass` functions as well (plus maybe some more like `baryon_number` and `lepton_number`) that would allow access to this information.  I'd keep this issue open for now.

**Comment by namurphy** [comment]
Closed by #239.
