### ISSUE TITLE
Documentation bug with inheritance diagrams

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/PlasmaPy#1838]
### Bug description

HTML issue? 

![image](https://user-images.githubusercontent.com/32618747/208449316-6a825b6b-68ce-4bd7-93af-9b96eca4419d.png)

### Package versions

Appears on the current `latest` branch of documentation (as of 12/19/2022)

**Comment by pheuer** [comment]
Same issue on charged_particle_radiography/synthetic_radiography doc page

![image](https://user-images.githubusercontent.com/32618747/208450279-6868d1d9-7d2a-413d-ab4d-34f6c8158184.png)

**Comment by StanczakDominik** [comment]
Quick hypothesis: missing graphviz dependency? That's going to have to be installed via apt-get or some such in the doc build on rtd.

**Comment by StanczakDominik** [comment]
I can do it once I've assembled my laptop back again.

**Comment by namurphy** [comment]
It appears I merged #1817 too soon! 😅 

I noticed this else too, like in the docs for [`fit_functions`](https://docs.plasmapy.org/en/latest/api_static/plasmapy.analysis.fit_functions.html#module-plasmapy.analysis.fit_functions), so it seems not to be specific to charged particle radiography.

**Comment by namurphy** [comment]
It looks like it's happening [in Sphinx's documentation](https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html#examples) too (see https://github.com/sphinx-doc/sphinx/issues/10948).  I also noticed that there were some [releases of `graphviz`](https://gitlab.com/graphviz/graphviz/-/releases) recently, so it may be the case that Sphinx will need to be correspondingly updated.  

My suspicion is that this is one of those upstream errors that'll likely get fixed if we wait, thanks to the people who maintain those packages.  Since this is a quiet time of year, my inclination is to wait and check back again in a few weeks.  The inheritance diagrams are still showing up okay on `stable`, at least.

**Comment by namurphy** [comment]
@SnoozeThis https://github.com/sphinx-doc/sphinx/issues/10948 -> remove label "Upstream fix required"

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/BJsdGrYGaDY) I will wait until https://github.com/sphinx-doc/sphinx/issues/10948 is closed and then remove label Upstream fix required.

**Comment by SnoozeThis** [comment]
Resolved.
