### ISSUE TITLE
Bring back Dependabot

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#1861]
The recent failures of CI in multiple places - https://github.com/PlasmaPy/PlasmaPy/commit/f36b7d766e998bc595bb6675a2f2d2208e4fbd8c, https://github.com/PlasmaPy/PlasmaPy/commit/9684bc8f5b834ecfb7360aec59695d1f49196fc5, and whichever one pinned tox to <4, show pretty unambiguously that we have a problem with versioning of our dependencies.

I've also heard recently that Dependabot no longer spams forks. I can't quite give you a source on that. But I'm willing to try.

So, my plan is:

- pin every dependency we have to <= what the newest version existing right now is
    * [ ] how does that work with dev dependencies?
- reenable dependabot and keep the upper bounds current

Then when something like pytest-xdist or tox or whatever breaks our CI, we know about it from the get-go.

I'll happily do it, but wanted to discuss first.

**Comment by namurphy** [comment]
Thanks for bringing this up!

If dependabot no longer spams forks (here's hoping!), then I think it would be good to enable it again and put upper limits on the `[docs,tests]` dependencies. I can't think of any downsides to doing that, in particular since we don't have much of a need to allow for compatibility with future versions of those packages.  Since the full suite of tests will be run when dependabot submits a PR, we can get an idea right away when things break.  Instead of spontaneous CI failures, we'll have well-planned CI failures!
