### ISSUE TITLE
Add mechanism to instantiate `CustomParticle` based off of positional arguments

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#1873]
### Feature description

I'd like it to be possible to put the mass and charge of a `CustomParticle` in either order as positional arguments.  For example, I would like to be able to do:
```pycon
>>> CustomParticle(1 * u.C)
>>> CustomParticle(1 * u.kg)
>>> CustomParticle(1 * u.kg, 1 * u.C)
>>> CustomParticle(1 * u.C, 1 * u.kg)
```

### Motivation

While working on #1871 and #1872, I've been having to do a bunch of special handling for when the input to `CustomParticle` is a charge or a mass, including when writing tests. Code downstream of `CustomParticle` will be cleaner if we have this flexibility.

### Implementation strategy

Right now the signature of `CustomParticle.__init__` is:
```
def __init__(self, mass: u.kg = None, charge: (u.C, Real) = None, symbol=None):
```
I'd like to be able to do `CustomParticle(1e-27 * u.kg)` or `CustomParticle(1e-18 * u.C)`, which would correspond to a signature like:
```
def __init__(self, *quantities, symbol=None):
```

This change would lead to breaking changes, so we might want to retain `mass` and `charge` as keyword arguments, even if we deprecate them.  We could perhaps even make it so that if a string is provided in `quantities`, it would get interpreted as the symbol (though `quantities` might not be the best name in that case).

### Additional context

This is inspired by #1364 and discussed further in #1872.  This should be addressed after #1866 is merged since they're both working on the same section of code.

**Comment by namurphy** [comment]
Thinking more broadly, we have a lot of formulary functions where we have arguments of different but unique physical types.  We could think about generalizing this approach to the formulary, since we can often uniquely identify which parameter a `Quantity` argument corresponds to based solely on its physical type.  This would wreak havoc with `validate_quantities`, though.

**Comment by StanczakDominik** [comment]
That last comment is interesting, but I don't think I fully grasp it just yet. Could you expand on it a little?

**Comment by namurphy** [comment]
Happy to share more!  I can say a bit about what I'm thinking, most of which is still in the brainstorming stage.

We have a lot of formulary functions with signatures like:
```Python
def Stańczak_Marikin_number(B, T, n, particle):
```
If one argument is provided with units convertible to m$^{-3}$, then we can safely conclude that this corresponds to `n`.  Similarly for `B` and `T`.  We could potentially create functionality such that we could do:
```pycon
>>> Stańczak_Marikin_number(1 * u.MK, 1e13 * u.m ** -3, 50 * u.G, "p+")
>>> Stańczak_Marikin_number(1e13 * u.m ** -3, 1 * u.MK, 50 * u.G, "p+")
>>> Stańczak_Marikin_number("p+", 1 * u.MK, 1e13 * u.m**-3, 50 * u.G)
```
The advantages would include greater flexibility for the user and less need to look up signatures.  The disadvantages would include possibly more complicated functions (unless we do this via a decorator), presumably a small performance penalty, and possibly less clear docstrings about what quantities are actually needed. I *think* this approach would lead to cleaner downstream code, but it could potentially lead to less clean code. In any case, we'd need to think about this pretty carefully.

Another alternative would be to have the approach be something like...
```
>>> plasma = Plasma(5 * u.T, 8e12 * u.m**-3, ...)
>>> Stańczak_Marikin_number(plasma)
```
...which is related to #812, and possibly #1008 also.

**Comment by StanczakDominik** [comment]
Personally, if I see a signature like the above, then seeing something like this in code:
> ```
> >>> Stańczak_Marikin_number(1 * u.MK, 1e13 * u.m ** -3, 50 * u.G, "p+")
> >>> Stańczak_Marikin_number(1e13 * u.m ** -3, 1 * u.MK, 50 * u.G, "p+")
> >>> Stańczak_Marikin_number("p+", 1 * u.MK, 1e13 * u.m**-3, 50 * u.G)
> ```

is going to be hellishly confusing, because on first instinct I don't remember or I'm not aware that this has a magical decorator that reshuffles the arguments so that they all fit the right slots. So suddenly all my knowledge of how Python handles arguments falls out the window.

And it gets worse, because most likely I'm not going to see that, I'm going to see this instead:

> ```
> >>> Stańczak_Marikin_number(1 * u.MK, 1e13 * u.m ** -3, 50 * u.G, "p+")
> >>> ... # other code
> >>> Stańczak_Marikin_number(1e13 * u.m ** -3, 1 * u.MK, 50 * u.G, "p+")
> >>> ... # yet other code
> >>> Stańczak_Marikin_number("p+", 1 * u.MK, 1e13 * u.m**-3, 50 * u.G)
> ```

So I see the second variation and I go, hey, isn't the first argument supposed to be a temperature? Why is this a volume...? 🤔

It's true that sometimes I don't want to remember the order of arguments. But if I roughly know what the function takes, Python has a delightful mechanism for that:

> ```
> >>> Stańczak_Marikin_number(T=1 * u.MK, n=1e13 * u.m ** -3, B=50 * u.G, particle="p+")
> ```

and I think we should instead promote writing code that uses that, instead.

So, all in all, you said yourself:

> In any case, we'd need to think about this pretty carefully.

And I think on careful thought, this would indeed result in making tests easier to write, but either be confusing to users or second-order-confusing to people who read code using our functionality. At this point, I'd just say, let's not do this.

Could you please point the special handling you wrote for #1871, #1872 instead? Perhaps there's another way to implement those that sidesteps the issue?

**Comment by StanczakDominik** [comment]
Another reason why I think danger lies this way... a magical decorator like this has failure modes, for example, a function that takes two densities. So we probably couldn't just use it everywhere, consistently - and I don't want to turn using the library into a game of "now which functions are magical enough for me to skip writing out the keyword names, and which aren't...?"!
