### ISSUE TITLE
User testing of contributor guide pages by new contributor on Windows

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2001]
In #1656, we did an overhaul of the contributor guide pages on [getting ready to contribute](https://docs.plasmapy.org/en/latest/contributing/getting_ready.html) and the [code contribution workflow](https://docs.plasmapy.org/en/latest/contributing/workflow.html).  While updating these pages, I went through the steps on Linux, but attempted to include instructions for Windows and macOS.

It would be incredibly helpful for someone who hasn't contributed to an open source project before to try out these steps on Windows, and provide suggestions and feedback on how we could improve it.  

The suggestions and feedback could either be in the form of replies to this issue, or a pull request by a new contributor that updates the guide directly.  For the latter, the guides are at [`docs/contributing/getting_ready.rst`](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/contributing/getting_ready.rst) and [`docs/contributing/workflow.rst`](https://github.com/PlasmaPy/PlasmaPy/blob/main/docs/contributing/workflow.rst) and are written in [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html).  

Many thanks!

Similar to: #2002

**Comment by martha889** [comment]
Hi! I would like to take this issue.

**Comment by namurphy** [comment]
@martha889 — that would be fantastic!  Thank you!

**Comment by martha889** [comment]
Suggestions for https://docs.plasmapy.org/en/latest/contributing/getting_ready.html

1. For people not using conda, should we also add steps for using venv to create a virtual environment? Also, use the `python` command instead of the `py` command.
2. Should we add a note regarding backward slashes in windows? Powershell commands still work with the forward slashes. But, the path `~/repos/PlasmaPy` automatically gets changed to  `~\repos\PlasmaPy`. 

Let me know if you think changes are needed for these and I will go ahead and make them. 

Can't find any improvements for the code contribution page workflow page.

**Comment by namurphy** [comment]
@martha889 — good ideas!  Please feel free to submit a pull request and make them!
