### ISSUE TITLE
Apparent bug in ion contribution to Thomson scattering spectrum

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2698]
We received a bug report over email.  

> I believe there may be a bug in the computation of the ion contribution for the Thomson scattering in diagnostics/thomson.py.  Specifically, the contribution from the species' charge ([line 247](https://github.com/PlasmaPy/PlasmaPy/blob/main/src/plasmapy/diagnostics/thomson.py#L247)) appears to be slightly incorrect. Rather than `ion_z​` it should be `ion_z**2 / zbar​` according to [Sheffield](https://www.sciencedirect.com/book/9780123748775/plasma-scattering-of-electromagnetic-radiation) (Section 5.1, Eq. 5.1.2 and following on page 104 - see screenshot below)
![unnamed](https://github.com/PlasmaPy/PlasmaPy/assets/8931994/a8ac4e2b-ef4f-4439-b07c-8192553f002c)

@pheuer — could you look into this?

**Comment by pheuer** [comment]
Thank you to whoever was looking this closely at the code! 

There may be an error here, but I was mislead for a minute because we already define the variable `zbar` in the code on line 175 as

$\bar z = \sum_j   N_j Z_j / \sum_k N_k$

Which is not the same as what I think the author here is suggesting, which based on the equation in Sheffield would be 

$\bar z_k = (\sum_j N_j Z_j ) / N_k$

The relation between them just being $\bar z  = \sum_k \bar z_k$
