### ISSUE TITLE
Describe how to use uv to install PlasmaPy

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#2858]
### Nature of improvement

It would be helpful to add a section to the installation instructions on how to use [uv](https://docs.astral.sh/uv/#getting-started) to activate and install PlasmaPy into a virtual environment.

### Location of improvement

This should go in the page on [installing PlasmaPy](https://docs.plasmapy.org/en/latest/install.html).  I would include it as the second option (after `pip` and before `conda`).  

### Additional context

`uv` is an "extremely fast Python package and project manager, written in Rust." One of the recent releases makes it so `uv` can be installed as a standalone package and then used to install different versions of Python itself.  It's getting pretty close to the point where I'd recommend `uv` as the best way to install Python itself! At least, for people who are comfortable with the command line.

**Comment by tien-vo** [comment]
Hi! I want to learn more about sphinx, so would like to contribute to this issue.

As I was editing the instructions, I thought plasmapy might want to provide a `uv.lock` file so that contributors can quickly [set up a working environment](https://docs.plasmapy.org/en/latest/contributing/getting_ready.html#setting-up-a-python-environment). Maybe an additional hook can generate this file?

**Comment by tien-vo** [comment]
> plasmapy might want to provide a `uv.lock` file

Just noticed #2852 :)
