### ISSUE TITLE
Put citation instructions in places

### ISSUE THREAD

**Issue by SolarDrew** [PlasmaPy/PlasmaPy#432]
To be more compliant with our code of conduct/vision statement (and particularly now we've released 0.1) we should consider making it clear how users should cite PlasmaPy by putting that info on the main GitHub page and somewhere prominent on the website, if it's not already

**Comment by namurphy** [comment]
We have had `CITATION.md` in our top-level directory, though that would need to be updated for our newest [PlasmaPy Community et al. (2018)](https://zenodo.org/record/1238132) reference.  It would be good to put this information on `README.md` on GitHub as well as the website and on docs.plasmapy.org, since `CITATION.md` is not really in a noticeable location.  I think I have things set up to get `0.1.1` archived on Zenodo as well when we make that release, in which case I'll be able to set up a persistent DOI identifier that automatically redirects to the most recently released version.

Thank you for bringing this up!

**Comment by StanczakDominik** [comment]
> following on from the creation of that issue: https://twitter.com/Sydonahi/status/991676513799102465

**Comment by lemmatum** [comment]
With respect to the Twitter image, [here](https://github.com/astroML/astroML/blob/0287fe00c429b28b3ddf52435a32543f43246349/astroML/__init__.py) is the example for how to implement `__citation__` in `__init__.py`.
