### ISSUE TITLE
Expand ITER example in `plot_physics`

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#448]
Raised from #428. Compare our functions' results to some actual data, etc. I can do that later, but if someone wants to do so, feel free to grab it!

**Comment by StanczakDominik** [comment]
Given that this is low priority and I've got deadlines coming down hard on me  I'd rather push this back to 0.3. this continues to be good for a newcomer!

**Comment by bryanluu** [comment]
Hi, I'm a newcomer to the Open Source scene but I'd love to try this out! May I give this a go?

**Comment by StanczakDominik** [comment]
Of course! Go right ahead :)

**Comment by bryanluu** [comment]
So I'm struggling to find data to compare the numbers to. I found the formulas in [Wikipedia](https://en.wikipedia.org/wiki/Plasma_parameters) but it seems redundant to just compare the numbers to the one's calculated by the formulas since that seems to be what's already done via `plasmapy`.

Another _very_ minor issue I found: the example in the code database uses the package `formulary` rather than `physics`, while the Jupyter notebook `.ipynb` uses `physics`. It's probably a good idea to make these consistent, at least in the comments (which don't match). I can do it for the `plot_physics` file if need be.

**Comment by StanczakDominik** [comment]
Just to keep discussion localized, I'm copypasting from Riot:

> If I remember correctly - this was a while ago - I think the idea behind this example was that we'd take parameters for a bunch of tokamaks and/or stellarators, plot those as scatter points in parameter space and use stuff from `formulary` to show how those machines compare to theoretical predictions plotted as curves

Of course the description here is completely disconnected from that, as I thought I'd just sit down the next day and do that. That, obviously, didn't work out.

**Comment by bryanluu** [comment]
I'm still rather confused about how the numbers from the papers I found could be compared to our data. I plotted the plasma frequency vs. electron density but the scale of the initial graph made these collapse to the single point. See my draft PR for details.

**Comment by namurphy** [comment]
I'm thinking that it would be helpful to expand the example to include plasma parameters for not just a tokamak and a stellarator, but also things like the solar corona, the solar wind at 1 AU, and the interstellar medium.  Here are some rough estimates.  The solar corona would be 1e6 K, 1e15 m⁻³, and B = 0.005 T.  The interstellar medium (specifically the warm neutral medium) would be 5000 K, 1e6 m⁻³, and B = 0.005 T.   The solar wind at 1 AU would be 1e5 K, 7e6 m⁻³, and B = 5e-9 T.  (cross-posted from Matrix)

**Comment by bryanluu** [comment]
Should we close this issue?

**Comment by StanczakDominik** [comment]
We should, thanks for the reminder!
