### ISSUE TITLE
.si in check_relativistic is extra slow

### ISSUE THREAD

**Issue by samurai688** [PlasmaPy/PlasmaPy#465]
Hi all,

I was making some plots with PlasmaPy today.  So my basic plan was, I have some arrays of densities and temperatures and magnetic fields, and I want to make some contour plots of various plasma parameters.  I didn't think plasmapy would be able to do vectorized operation on the numpy arrays, so I said, screw it, I'll just loop through each array and do each one individually.

Well. I knew it would be slow, but it was even slower than I expected. I ran it through the profiler and I think some of it is from Python itself, some of it is from the astropy units stuff, but then there was a massive amount of time in check_relativistic due to the use of the .si function on the astropy units, somehow.  Apparently that function is really slow?  I'm going to see if we can avoid the use of it.

**Comment by lemmatum** [comment]
Nice! Thanks for looking into this!

**Comment by SolarDrew** [comment]
Yes, thanks for pointing this out @samurai688 :D From looking at the units docs, I _think_ this might be because `.si` always returns a copy of the unit. Since the units will always cancel anyway, we might be able to do `(V / c).to_value(u.dimensionless_unscaled)` instead, which will return a view of the array if the unit conversion isn't necessary, which may save a little time.
