### ISSUE TITLE
Astrophysics Source Code Library

### ISSUE THREAD

**Issue by zenitani** [PlasmaPy/PlasmaPy#594]
Why don't you register PlasmaPy to Astrophysics Source Code Library (https://ascl.net/)?

**Comment by namurphy** [comment]
So far we have been archiving PlasmaPy's releases in the [PlasmaPy Community](https://zenodo.org/communities/plasmapy) on [Zenodo](https://zenodo.org).  I finally had a chance to ask the head librarian here if we should both archive PlasmaPy on Zenodo and register it on ASCL.  She strongly recommended against it, but for different reasons that I thought.  The problem she brought up is that an ASCL record does not point to a unique digital object.  Some records point to GitHub repositories that are frequently changing, and other records point to both code and journal articles.  If someone used Astropy for a paper and cited its ASCL record, then a reader would not be able to tell which version of Astropy was used for the research described in the paper, which makes it harder to reproduce results.  I hadn't realized that this was a problem before, so it was kind of surprising.

**Comment by owlice** [comment]
Oh, interesting. Clearly we need to do better outreach to libraries/librarians.

The ASCL's recommended citation method for its entries is to **include the version number of the software** in the citation; please see here for more information: 
https://ascl.net/home/getwp/351  

The ASCL lists authors' preferred citation methods for entries when we know what they are. Here are a few ASCL entries that show the wide variety of citation methods that code authors request: 
https://ascl.net/1803.005 (Kadenza)
http://ascl.net/9910.001 (Cloudy)
http://ascl.net/1801.012 (RadVel)

In the case of AstroPy, that community's preferred citations are the two papers describing the code (see here: https://www.astropy.org/acknowledging.html and here: http://ascl.net/1304.002), so one should never use the ASCL entry to cite that software.

If one is interested in transparency and reproducibility (and everyone should be) of research, one should always specify what version or hash of  **any** software was used, regardless of the citation method.

All of that said, it appears PlasmaPy doesn't quite at this time meet the criteria for inclusion in the ASCL (listed here: http://ascl.net/home/getwp/1354) anyway, so that's a valid reason for not registering it yet.

Alice
ASCL editor

**Comment by StanczakDominik** [comment]
I guess this can be closed thanks to the amazing @owlice putting us onto ASCL at http://ascl.net/1906.019 :)
