### ISSUE TITLE
Too many custom exceptions

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#612]
I get it, sometimes when you're programming everything looks like a base class. On second thought, I really take issue with this, though:

https://github.com/PlasmaPy/PlasmaPy/blob/c560583ee731aca18cb3562ef8240fc43da9d502/plasmapy/__init__.py#L19-L24

This is the only place `UnsupportedPythonError` gets called in PlasmaPy. And given that we have https://github.com/PlasmaPy/PlasmaPy/blob/c560583ee731aca18cb3562ef8240fc43da9d502/plasmapy/utils/exceptions.py, I think this might be a common antipattern.

A bunch of `atomic` exceptions (better located in `atomic`, perhaps?) is probably fine. Likewise for `RelativityException` etc (though it might be worthwhile just `nan`ing that output). But things like this we're probably better off without!

**Comment by namurphy** [comment]
The `UnsupportedPythonError` originally came from Astropy, I think!  But yes, I agree that something like a standard `ImportError` with a descriptive error message would be better in that case.  

I'm also in agreement that the `atomic` exceptions should be located in `atomic`.  Having the different `atomic` exceptions is useful because they help with exception handling.  The different types of `atomic` exceptions sometimes need to get handled different.  We might be able to combine some of them though.

We should make sure to have exceptional exceptions!

**Comment by namurphy** [comment]
Come to think of it, defining `UnsupportedPythonError` here would make exception handling kind of difficult.  A user wouldn't have access to `plasmapy.UnsupportedPythonError` unless `plasmapy` was able to be imported.

```Python
try:
    import plasmapy
except plasmapy.UnsupportedPythonError:
    ...
```

**Comment by StanczakDominik** [comment]
Exactly! Getting rid of this one and splitting up exceptions.py is the
least I can do. I'll get on it once I'm back home.
