### ISSUE TITLE
Posible bug in  function mass_density

### ISSUE THREAD

**Issue by diego7319** [PlasmaPy/PlasmaPy#708]
Hello, while adding some examples into the documentation I faced something weird:
- Im trying to run this code but its gives me an error
`>>>from astropy import units as u`
`>>>from plasmapy.formulary import mass_density; `
`>>>mass_density(density=1 * u.m ** -3, particle='p')`
`<Quantity 1.67353284e-27 kg / m3> `
`>>>mass_density(density=1 * u.m ** -3)`
` File "D:\python\PlasmaPy\plasmapy\formulary\parameters.py", line 102, in mass_density    `                                 `raise ValueError(f"You must pass a particle (not {particle}) to calculate the "      `                               `ValueError: You must pass a particle (not None) to calculate the mass density! `

and if we read the documentation it says its optional

> particle (str, optional) – Representation of the particle species (e.g., 'p' for protons, 'D+' for deuterium, or 'He-4 +1' for singly ionized helium-4), which defaults to electrons. If no charge state information is provided, then the particles are assumed to be singly charged.

**Comment by StanczakDominik** [comment]
I just checked, this is actually fine-ish, because you can't turn a concentration, or number of particles per volume, into a mass density, or number of kilograms per volume, without either:

* knowing what the mass of each particle is (thus the particle argument), or
* supplying the mass density itself (which may seem nonsensical until you look at the function's docstring: `Utility function to merge two possible inputs for particle charge.`)

So I would say the ValueError's content should be changed to something like "ValueError: __If passing a number density,__ you must pass a particle (not None) to calculate the mass density!"

Wanna implement that real quick? :)

**Comment by diego7319** [comment]
I dont think I have time now its 01:00 where Im from, but I will verify this with the version that is used on the plasmapy-benchmarks project I dont remember having any error with it.

**Comment by StanczakDominik** [comment]
Hmm, it could very well be that we broke something untested recently. All right, in the meantime, sleep well! :zzz:

**Comment by diego7319** [comment]
My mistake, using a previous version of plasmapy I run into the same error, I will change the ValueError part on the same pull along with the new examples for the documentation and I dont know if I may add my name to the credits.rst file or wait  for someone to do it.
