### ISSUE TITLE
[PIC] Particle to density and Fields to particle

### ISSUE THREAD

**Issue by antoinetavant** [PlasmaPy/PlasmaPy#81]
task of #69 , for a PIC simulation
Passing from the particle to the field : 
- [ ] linear weighting via "inverse area" of the particle to the plasma density field
From the field to the particle
- [x] calculate the electric and magnetizable field via 1D or 2D interpolation.

This task is not complicated, but it is the interface between the Plasma and the Particle instances. This interface should be well thought

**Comment by tulasinandan** [comment]
@colbych has a nice interpolation routine in his Py3D package. We could port that as a starting point instead of writing a new one. 

Also this is a generic enough task that is very useful even outside PIC simulation. One example would be taking a cut across an array with a step size that does not always fall on the grid.

We should also make sure that it is general enough to take different shape factors for interpolation.
