### ISSUE TITLE
Add property-based testing

### ISSUE THREAD

**Issue by StanczakDominik** [PlasmaPy/PlasmaPy#863]
I've been reading about property-based testing recently, and I think adding [Hypothesis](https://hypothesis.readthedocs.io/en/latest/ to our tests could potentially help us find some bugs we don't know about just yet! For example, #726 could probably have been found earlier in that way.

I think the best place to try adding those would be the simple functions in `formulary`.

**Comment by kab11** [comment]
Hey @StanczakDominik, can I work on this issue?

**Comment by StanczakDominik** [comment]
Sure @kab11, go right ahead :)

**Comment by namurphy** [comment]
✅ Closing this as completed since we've added property based testing in a few places (such as for `plasma_dispersion_func` and `plasma_dispersion_func_deriv` in #1249), and have a short discussion & link to `hypothesis` in the testing guide. Since adding tests with `hypothesis` is often a good first contribution, it would be great to follow up with future issues to add property-based testing to specific functionality where it would be helpful.  Thank you for raising this!
