### ISSUE TITLE
Change name of chat room from Matrix/Riot to Element

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy#890]
The name of the chat platform we are using has [changed from Matrix/Riot to Element](https://element.io/blog/the-world-is-changing/).  We should change the name of our chat room accordingly, including in our README file and possibly some places in our documentation.

**Comment by namurphy** [comment]
The link of the chat room is now: `https://app.element.io/#/room/#plasmapy:openastronomy.org`

**Comment by StanczakDominik** [comment]
The interesting thing here:

* Matrix is the chat platform we were and still are using;
* Riot is the old name of the particular chat client we're using;
* Element is the new name for that chat client.

> nowadays there are lots of other Matrix clients, vendors and hosting providers that demonstrate perfectly the diversity of the Matrix ecosystem.

(from the linked page)

So I'm going to standardize this to Matrix in most cases, but link to Element. I guess we could link to https://matrix.to/#/#plasmapy:openastronomy.org (I found the site by looking at what provides the ![Matrix](https://matrix.to/img/matrix-badge.svg) badge), but since Matrix is a bit niche as is, having the chat another step away and making people decide which chat client to use seems counterproductive.

Also, it's sad that they couldn't get the element.im domain - I liked that for Instant Messaging. Instead of that they went from riot.im/app (cool!) they went to app.element.io (generic!). Oh well.
